# Generated by Django 3.2.4 on 2021-07-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_head_offer_photo_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_offer_photo_section',
            name='Notice',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='head_offer_photo_section',
            name='picture',
            field=models.ImageField(default=None, upload_to='HeadOfferPhotoSection/'),
        ),
    ]
