# Generated by Django 3.2.4 on 2021-07-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210707_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_offer_photo_section',
            name='Notice',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
