# Generated by Django 3.2.4 on 2021-07-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20210710_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic2',
            field=models.ImageField(default='default_pic.webp', upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic3',
            field=models.ImageField(default='default_pic.webp', upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic4',
            field=models.ImageField(default='default_pic.webp', upload_to='picture/'),
        ),
    ]
