# Generated by Django 3.2.4 on 2021-07-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20210710_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic4',
        ),
    ]
